name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:wifi-left/Map-MiniGames.git
          ssh_private_key:
            ${{ secrets.SSH_KEY2 }}
      - name: 'Mirror to Gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:wifi-left/Map-MiniGames.git
          ssh_private_key:
            ${{ secrets.SSH_KEY2 }}